config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
     resources :streams
     end
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stream.rb
class Stream < ApplicationRecord
end

app/controllers/api/v1/streams_controller.rb
class Api::V1::StreamsController < ApplicationController
  before_action :set_stream, only: [:show, :update, :destroy]
  skip_before_action :verify_authenticity_token
  # GET /streams
  def index
   @streams = Stream.all
   render json: @streams
  end
  # GET /streams/1
  def show
   render json: @stream
  end
  # POST /streams
  def create
   @stream = Stream.new(stream_params)
   if @stream.save
    render json: @stream, status: :created, location:        api_v1_stream_url(@stream)
   else
    render json: @stream.errors, status: :unprocessable_entity
   end
  end
  # PATCH/PUT /streams/1
  def update
   if @stream.update(stream_params)
    render json: @stream
   else
    render json: @stream.errors, status: :unprocessable_entity
   end
  end
 # DELETE /streams/1
  def destroy
   @stream.destroy
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_stream
   @stream = Stream.find(params[:id])
  end
  # Only allow a trusted parameter “white list” through.
  def stream_params
  params.require(:stream).permit(:title, :description)
  end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Streams</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/streams/_form.html.erb
<%= form_with(model: stream, local: true) do |form| %>
  <% if stream.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stream.errors.count, "error") %> prohibited this stream from being saved:</h2>

      <ul>
      <% stream.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/streams/edit.html.erb
<h1>Editing Stream</h1>

<%= render 'form', stream: @stream %>

<%= link_to 'Show', @stream %> |
<%= link_to 'Back', streams_path %>

app/views/streams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Streams</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @streams.each do |stream| %>
      <tr>
        <td><%= stream.title %></td>
        <td><%= stream.description %></td>
        <td><%= link_to 'Show', stream %></td>
        <td><%= link_to 'Edit', edit_stream_path(stream) %></td>
        <td><%= link_to 'Destroy', stream, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stream', new_stream_path %>

app/views/streams/new.html.erb
<h1>New Stream</h1>

<%= render 'form', stream: @stream %>

<%= link_to 'Back', streams_path %>

app/views/streams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @stream.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @stream.description %>
</p>

<%= link_to 'Edit', edit_stream_path(@stream) %> |
<%= link_to 'Back', streams_path %>